apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  labels: 
    app: guestbook
    tier: frontend
spec: 
  selector: 
      app: guestbook
      tier: frontend
  ports: 
  - port: 80
  type: LoadBalancer

         #note: if loadbalancer is pending or notworrking use type: NodePort instead of LoadBalancer
