apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsdeploy
  labels: 
   app: jenkins
   tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: jenkins
      tier: frontend
  template:
    metadata:
      labels:
        app: jenkins
        tier: frontend
    spec:
      containers:
      - name: jenkins-container
        image: jenkins:latest
        ports: 
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-frontend-service
  labels: 
    app: jenkins
    tier: frontend
spec:
  type: NodePort 
  selector: 
    app: jenkins
    tier: frontend
  ports: 
  - port: 8080

