apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
    matchExpressions:
    - {key: tier , operator: In , values: [frontend]}
  template:
    metadata:
      name: apche-pod
      labels:
        app: apache
        tier: frontend
    spec:
      containers:
      - name: apache
        image: tomcat:latest
        ports:
        - containerPort: 80
